package com.learn.englishadventures.game_logic

object WordBank {
    // Ensure there are at least 300 unique words across the lists.
    val easyWords = listOf(
        "CAT", "DOG", "BOOK", "TREE", "BALL", "FOOD", "HAND", "BIRD", "FISH", "STAR",
        "SUN", "MOON", "RAIN", "SNOW", "WIND", "FROG", "BEAR", "LION", "DUCK", "MILK",
        "BREAD", "WATER", "SALT", "SUGAR", "APPLE", "GRAPE", "PEACH", "PEAR", "PLUM", "MANGO",
        "CHAIR", "TABLE", "PHONE", "CLOCK", "SHOE", "COAT", "HAT", "PANTS", "JEANS", "CUP",
        "PLATE", "SPOON", "FORK", "KNIFE", "BAG", "KEY", "DOOR", "WALL", "FLOOR", "ROOF",
        "RIVER", "LAKE", "HILL", "ROAD", "CITY", "TOWN", "VILLAGE", "FIELD", "FARM", "SHEEP",
        "GOAT", "COW", "CALF", "PIG", "HEN", "EGG", "NEST", "LEAF", "ROOT", "STEM",
        "BUSH", "GRASS", "SOIL", "SAND", "ROCK", "STONE", "METAL", "GOLD", "IRON", "SILK",
        "WOOD", "PAPER", "PEN", "INK", "NOTE", "MAP", "BOOKS", "CANDY", "BERRY", "LEMON",
        "OLIVE", "BASIL", "MINT", "RICE", "BEAN", "LENTIL", "PASTA", "BREADS", "SAUCE", "CHEESE",
        "HONEY", "BUTTER", "YOGURT", "CREAM", "JUICE", "SODA", "TEA", "COFFEE", "COCOA", "BISCUIT"
    )

    val mediumWords = listOf(
        "HOUSE", "GARDEN", "KITCHEN", "FRIEND", "SCHOOL", "MARKET", "BRIDGE", "STATION", "AIRPORT", "LIBRARY",
        "MUSEUM", "THEATER", "HOSPITAL", "OFFICE", "FACTORY", "VILLAGER", "TEACHER", "STUDENT", "DRIVER", "PAINTER",
        "WRITER", "READER", "LISTENER", "SINGER", "DANCER", "ATHLETE", "CAPTAIN", "MANAGER", "ENGINEER", "DESIGNER",
        "DEVELOPER", "PROGRAM", "PACKAGE", "PROJECT", "NETWORK", "SERVER", "CLIENT", "BROWSER", "WINDOW", "BUTTON",
        "BATTERY", "CAMERA", "SCREEN", "KEYBOARD", "MOUSE", "PRINTER", "MONITOR", "SPEAKER", "HEADSET", "CHARGER",
        "BICYCLE", "MOTORCAR", "HIGHWAY", "SUBWAY", "TUNNEL", "BRACKET", "COMPASS", "RULER", "ERASER", "MARKERS",
        "PENCIL", "NOTEBOOK", "BACKPACK", "LUNCHBOX", "UMBRELLA", "RAINCOAT", "SUNGLASS", "SHAMPOO", "TOOTHPASTE", "TOOTHBRUSH",
        "LAUNDRY", "WARDROBE", "BALCONY", "BASEMENT", "BEDROOM", "BATHROOM", "KITCHENS", "DINING", "LIVING", "CORRIDOR",
        "PLAYROOM", "GARAGES", "WORKSHOP", "GARDENER", "FLOWERED", "SEASIDE", "MOUNTAIN", "FOREST", "DESERT", "ISLAND",
        "CANYONS", "PLATEAU", "PRAIRIE", "VALLEYS", "OCEANIC", "COASTAL", "HARBORS", "LIGHTING", "HEATING", "COOLING"
    )

    val hardWords = listOf(
        "COMPUTER", "LANGUAGE", "ELEPHANT", "ADVENTURE", "SCIENCE", "KNOWLEDGE", "ALGORITHM", "ARCHITECT", "METAPHOR", "SYNTHESIS",
        "PHILOSOPHY", "QUANTIFIED", "STATISTICS", "ASTRONOMY", "GEOGRAPHY", "CALCULUS", "PROBABILITY", "DIFFERENTIAL", "THERMODYNAMIC", "PHOTOSYNTHESIS",
        "MICROBIOLOGY", "BIOLUMINESCENT", "ELECTROMAGNETIC", "TRANSFORMATION", "CONFIGURATION", "INTERPOLATION", "HYPOTHESIS", "CONSERVATION", "SUPERPOSITION", "ENTANGLEMENT",
        "SEMICONDUCTOR", "CRYPTOGRAPHY", "VISUALIZATION", "OPTIMIZATION", "VIRTUALIZATION", "CONCURRENCY", "PARALLELISM", "SERIALIZATION", "REFLECTION", "ABSTRACTION",
        "DETERMINISTIC", "STOCHASTIC", "RECURSION", "COMPOSITION", "DECOMPOSITION", "INVARIANT", "IDEMPOTENCE", "COMMUTATIVE", "ASSOCIATIVE", "DISTRIBUTIVE",
        "BIOINFORMATICS", "NEUROSCIENCE", "PSYCHOLINGUISTICS", "ANTHROPOLOGY", "ARCHEOLOGY", "PALEONTOLOGY", "SEISMOLOGY", "METEOROLOGY", "OCEANOGRAPHY", "CRYSTALLOGRAPHY",
        "EPISTEMOLOGY", "ONTOLOGY", "HERMENEUTICS", "PHENOMENOLOGY", "HISTORIOGRAPHY", "SEMANTIC", "PRAGMATICS", "MORPHOLOGY", "SYNTAX", "PHONOLOGY",
        "THERAPEUTICS", "PHARMACOLOGY", "ANESTHESIOLOGY", "CARDIOLOGY", "NEPHROLOGY", "DERMATOLOGY", "HEMATOLOGY", "ENDOCRINOLOGY", "IMMUNOLOGY", "GASTROENTEROLOGY"
    )
}
