name: Android Release (Unsigned)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

  - name: Install SDKMAN and Gradle 8.7
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle --version

      - name: Generate Gradle Wrapper (8.7)
        run: |
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          gradle wrapper --gradle-version 8.7

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      - name: Show sdkmanager version (diagnostic)
        run: |
          which sdkmanager || true
          sdkmanager --version || true

      - name: Build Release (Unsigned)
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon :app:assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: app/build/outputs/apk/release/*.apk
